server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.129.212.155:3306/lifadian?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: georgechen
    url: jdbc:mysql://localhost:3306/lifadian?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: 骏泰理发店管理系统后台
logging:
  level:
    com:
      chen:
        lifaapi:
          mapper: debug
mybatis:
  type-aliases-package: com.chen.lifaapi.entity
  mapper-locations: classpath:mapper/*.xml

#swagger地址:http://localhost:8089/swagger-ui/#/
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0??Demo
  try-host: http://localhost:${server.port}
